### ISSUE TITLE
Backend Web Frameworks

### ISSUE THREAD

**Issue by KairuRengu** [KairuRengu/CP-317-Project#3]
Django (python)
CakePHP (php)
NodeJs (javascript)
Dart (Dart programming language by google)
Flask (python)

We can probably choose from any of these if we want to pick a backend server side framework to use. We can decide on this on a later date after the app requires more of this.

**Comment by ShawnCramp** [comment]
Personally I would like to learn Django.  But if and when we need to choose, I'm not picky

**Comment by KairuRengu** [comment]
Django it is then.
